[platformio]
default_envs = node, gateway

[env]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_src_filter = +<${PIOENV}/>
build_flags =
    -I include

[env:node]
lib_deps =
    ropg/Heltec_ESP32_LoRa_v3
    adafruit/Adafruit AHTX0 @ ^2.0.5
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
	https://github.com/boschsensortec/BSEC-Arduino-library.git
build_flags =
    ${env.build_flags}
    -L".pio/libdeps/node/BSEC Software Library/src/esp32"
	-lalgobsec

[env:gateway]
lib_deps =
    ropg/Heltec_ESP32_LoRa_v3
    bblanchon/ArduinoJson
build_flags =
    ${env.build_flags}
    -D ARDUINO_LOOP_STACK_SIZE=24576

[env:gateway_self_test]
lib_deps =
    ropg/Heltec_ESP32_LoRa_v3
    bblanchon/ArduinoJson
build_flags =
    ${env.build_flags}
    -D WEDS_TREND_SAMPLE_INTERVAL_SEC_OVERRIDE=10
    -D ARDUINO_LOOP_STACK_SIZE=24576
