[platformio]
default_envs = node

[env]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    jgromes/RadioLib @ ^7.3.0
build_src_filter = +<${PIOENV}/>
build_flags = -D SENSOR_MODE


[env:node]

; [env:node_with_simulation]
; build_src_filter = +<node/>
; build_flags = -D SIMULATION_MODE

; [env:node_with_file_simulation]
; build_src_filter = +<node/>
; build_flags = -D FILE_SIMULATION_MODE


[env:gateway]
