[platformio]
default_envs = node

[env]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    jgromes/RadioLib @ ^7.3.0
build_src_filter = +<${PIOENV}/>
build_flags = -D SENSOR_MODE


[env:node]

lib_deps =
    jgromes/RadioLib @ ^7.3.0
    adafruit/Adafruit AHTX0 @ ^2.0.5
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/Adafruit BME680 Library @ ^2.0.4
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14

; [env:node_with_simulation]
; build_src_filter = +<node/>
; build_flags = -D SIMULATION_MODE

; [env:node_with_file_simulation]
; build_src_filter = +<node/>
; build_flags = -D FILE_SIMULATION_MODE


[env:gateway]
lib_deps =
    jgromes/RadioLib @ ^7.3.0
