; Imposta quale ambiente viene compilato di default se premi la spunta "Build"
; (Puoi cambiarlo in "server" all'occorrenza, o usare l'interfaccia di VSCode)
[platformio]
default_envs = logger

; --- IMPOSTAZIONI COMUNI A TUTTI GLI AMBIENTI ---
[env]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
; Questa flag esclude tutto e include solo la cartella src/nome_ambiente/
build_src_filter = +<${PIOENV}/> 

; --- AMBIENTE 1: REGISTRAZIONE DATI ---
[env:logger]
board = esp32doit-devkit-v1
lib_deps =
  adafruit/Adafruit AHTX0 @ ^2.0.5
  adafruit/Adafruit BMP280 Library @ ^2.6.8
  adafruit/Adafruit BME680 Library @ ^2.0.4
  adafruit/DHT sensor library @ ^1.4.6
  adafruit/Adafruit Unified Sensor @ ^1.1.14

; --- AMBIENTE 2: RECUPERO DATI VIA WIFI ---
[env:server]
; board = esp32doit-devkit-v1

; Nessuna libreria esterna necessaria, WiFi, WebServer e LittleFS sono built-in

[env:logger_bme_only]
lib_deps =
  https://github.com/boschsensortec/BSEC-Arduino-library.git

build_flags = 
  -L".pio/libdeps/logger_bme_only/BSEC Software Library/src/esp32"
  -lalgobsec