# -*- coding: utf-8 -*-
"""WEDS_Risk_Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AO72YTZmIA-dFu1zoFOem-O-mRa_ggXP
"""

from google.colab import drive
drive.mount('/content/drive')

"""# NETCDF4

__netcdf4__ is the engine used to handle _.nc_ files.
"""

!pip install netcdf4 h5netcdf dask

import os
import xarray as xr
import glob

weather_path = '/content/drive/MyDrive/Datasets/WEDS - RiskScore/weather_data_w/'
fire_path = '/content/drive/MyDrive/Datasets/WEDS - RiskScore/fire_data/'

wf_pattern = weather_path + 'era5_*.nc'
ff_pattern = fire_path + 'cams_*.nc'

if os.path.exists(weather_path):
    files = glob.glob(wf_pattern)
    if files:
        print(f'<SUCCESS> Found {len(files)} file(s).')
    else:
        print('<WARNING> Empty directory.')
else:
    print('<WARNING> Path does not exist.')

if os.path.exists(fire_path):
  files = glob.glob(ff_pattern)
  if files:
    print(f'<SUCCESS> Found {len(files)} file(s).')
  else:
    print('<WARNING> Empty directory.')
else:
  print('<WARNING> Path does not exist')

raw_wds = xr.open_mfdataset(
    wf_pattern,
    combine='by_coords',
    engine='h5netcdf'
)

if 'time' in raw_wds.dims:
    raw_wds = raw_wds.squeeze('time')

w_ds = raw_wds.resample(valid_time='1D').mean()

raw_fds = xr.open_mfdataset(
    ff_pattern,
    engine='h5netcdf',
)

f_ds = raw_fds

print("Daily weather Dataset:")
print(w_ds)

print("Daily fire Dataset:")
print(f_ds)

import numpy as np
import xarray as xr

# 1. Unifichiamo i chunk temporali per evitare il ValueError sulla finestra mobile
w_ds = w_ds.chunk({'valid_time': -1})

# 2. Calcolo Feature Meteo Istantanee
temp_c = w_ds['t2m'] - 273.15
dew_c = w_ds['d2m'] - 273.15
es = 6.112 * np.exp((17.67 * temp_c) / (temp_c + 243.5))
e = 6.112 * np.exp((17.67 * dew_c) / (dew_c + 243.5))
w_ds['rh'] = ((e / es) * 100).clip(0, 100)
w_ds['temp_c'] = temp_c

# 3. Calcolo Medie Settimanali (con min_periods=1 per non perdere i primi giorni)
w_ds['avgw_rh'] = w_ds['rh'].rolling(valid_time=7, center=False, min_periods=1).mean()
w_ds['avgw_temp'] = w_ds['temp_c'].rolling(valid_time=7, center=False, min_periods=1).mean()

# 4. Calcolo Differenze (Delta) rispetto a ieri
w_ds['temp_delta'] = w_ds['temp_c'].diff(dim='valid_time', n=1)
w_ds['rh_delta'] = w_ds['rh'].diff(dim='valid_time', n=1)

# 5. Pulizia, Rinomina e Allineamento
w_ds = w_ds.rename({
    't2m': 'temp_k',
    'sp': 'pressure'
})

f_ds = f_ds.rename({
    'cofire': 'smoke_index',
    'frpfire': 'fire_intensity'
})

# wind feature
w_ds['wind_speed'] = np.sqrt(w_ds['u10']**2 + w_ds['v10']**2)

w_ds['wind_dry_factor'] = w_ds['wind_speed'] / (w_ds['rh'] + 1)

print("<SUCCESS> Successfully initialized features.\n")

f_ds = f_ds.interp_like(w_ds, method='nearest')
print('<SUCCESS> Dataset successfully aligned.\n')

# 6. Merge Finale
ds = xr.merge([w_ds, f_ds])

print("Merged Dataset con Feature Estese:")
print(ds)

"""# DataFrame Creation

There is performed the task to create and polish the dataframe.
"""

df = ds.to_dataframe().reset_index()

FEATURES = ['temp_c', 'rh', 'pressure', 'smoke_index', 'fire_intensity', 'avgw_temp', 'avgw_rh', 'temp_delta', 'rh_delta']

df = df.dropna(subset=FEATURES)

df['target'] = (df['fire_intensity'] > 1e-9).astype(int)

print(f"Dataset has {len(df)} rows.")
print(df[FEATURES + ['target']].head())

"""## DataFrame Info

Run the following code cell to obtain info about the dataset.
"""

stats = df[FEATURES].describe()
print(stats)

comparison = df.groupby('target')[FEATURES].mean()
print("Medie comparate:")
print(comparison)

counts = df['target'].value_counts()
percentages = df['target'].value_counts(normalize=True) * 100

print(f"Righe senza incendio (0): {counts[0]} ({percentages[0]:.2f}%)")
print(f"Righe con incendio (1):    {counts[1]} ({percentages[1]:.2f}%)")

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 8))
correlation_matrix = df[FEATURES + ['target']].corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlazione tra parametri meteo e incendi")
plt.show()

"""## Data Splitting"""

!pip install tensorflow

import numpy as np
from sklearn.model_selection import train_test_split

features = ['temp_c', 'rh', 'pressure', 'avgw_temp', 'avgw_rh', 'temp_delta', 'rh_delta']
X = df[features]
y = df['target']

""" 60% train, 20% validation, 20% test """
# stratify=y makes the split omogenous wrt y so 'target' this is necessary due to data imbalance.
X_train, X_remain, y_train, y_remain = train_test_split(X, y, test_size=0.40, stratify=y, random_state=42)

X_val, X_test, y_val, y_test = train_test_split(X_remain, y_remain, test_size=0.50, stratify=y_remain, random_state=42)

print(f"<SUCCESS> Dataset successfully splitted.\n\nTraining set: {len(X_train)} rows.\nValidation set: {len(X_val)} rows.\nTest set: {len(X_test)} rows.")

"""## Statistics

### Temperature Distribution

The following cell create a plot which make it possible to visualize the temperature distribution with respect to fire or no fire.
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))

temp_no_fire = X_val[y_val == 0]['temp_c']
temp_fire = X_val[y_val == 1]['temp_c']

# Creiamo l'istogramma
plt.hist(temp_no_fire, bins=50, alpha=0.5, label='No Fire', density=True)
plt.hist(temp_fire, bins=50, alpha=0.5, label='Fire', color='red', density=True)

plt.xlabel('Temperature (°C)')
plt.ylabel('Probability')
plt.title('Temperature distribution: Fire vs No Fire')
plt.legend()
plt.show()

"""### Temperature vs Humidity

Here is visualized the relation between temperature and humidity in presence of fire.
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 7))

df_no_fire = X_val[y_val == 0].sample(20000, random_state=42)
df_fire = X_val[y_val == 1]

plt.scatter(df_no_fire['temp_c'], df_no_fire['rh'],
            color='royalblue', alpha=0.1, s=10, label='No Fire')

plt.scatter(df_fire['temp_c'], df_fire['rh'],
            color='red', alpha=0.6, s=20, label='Fire')

plt.xlabel('Temperature (°C)')
plt.ylabel('Relative Humidity (%)')
plt.title('Relation between Temperature and Humidity')
plt.legend()
plt.grid(alpha=0.3)
plt.show()

"""## Data Normalization"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

print("<SUCCESS> Dataset successfully normalized.\n")

"""# Model"""

import tensorflow as tf
from tensorflow.keras import layers, models

model_v1 = models.Sequential([
    # Opzione 1: Definiamo l'input usando uno strato dedicato (più moderno)
    layers.Input(shape=(X_train_scaled.shape[1],)),

    layers.Dense(32, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.2),

    # Primo strato denso
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.2),

    # Hidden Layers
    layers.Dense(32, activation='relu'),
    layers.Dense(16, activation='relu'),

    # Output Layer
    layers.Dense(1, activation='sigmoid')
])

# Compilazione
model_v1.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=[
        tf.keras.metrics.Precision(name='precision'),
        tf.keras.metrics.Recall(name='recall'),
        tf.keras.metrics.AUC(name='auc')
    ]
)

model_v1.summary()

import tensorflow as tf
from tensorflow.keras import layers, models

def build_precision_model(input_shape):
    model = models.Sequential([
        layers.Input(shape=input_shape),

        # Primo blocco: Espansione e Normalizzazione
        layers.Dense(128),
        layers.LeakyReLU(negative_slope=0.01), # Più robusto della ReLU
        layers.BatchNormalization(),

        # Secondo blocco: Contrazione (Bottleneck)
        layers.Dense(64),
        layers.LeakyReLU(negative_slope=0.01),
        layers.Dropout(0.3), # Protezione dai falsi positivi

        layers.Dense(32),
        layers.LeakyReLU(negative_slope=0.01),
        layers.BatchNormalization(),

        # Terzo blocco: Fine-tuning
        layers.Dense(16, activation='relu'),

        # Output: Risk Score
        layers.Dense(1, activation='sigmoid')
    ])

    # Optimizer con Learning Rate ridotto per maggiore stabilità
    opt = tf.keras.optimizers.Adam(learning_rate=0.0001)

    model.compile(
        optimizer=opt,
        loss='binary_crossentropy',
        metrics=[
            tf.keras.metrics.Precision(name='precision'),
            tf.keras.metrics.Recall(name='recall'),
            tf.keras.metrics.AUC(name='pr_auc', curve='PR') # Focus sulla curva Precision-Recall
        ]
    )
    return model

# Crea il modello
model_v2 = build_precision_model((X_train_scaled.shape[1],))
model_v2.summary()

import tensorflow as tf
from tensorflow.keras import layers, models

def build_precision_model(input_shape):
    model = models.Sequential([
        layers.Input(shape=input_shape),

        # Primo blocco: Espansione e Normalizzazione
        layers.Dense(128),
        layers.LeakyReLU(negative_slope=0.01), # Più robusto della ReLU
        layers.BatchNormalization(),

        # Secondo blocco: Contrazione (Bottleneck)
        layers.Dense(16),
        layers.LeakyReLU(negative_slope=0.01),

        layers.Dense(64),
        layers.LeakyReLU(negative_slope=0.01),
        layers.Dropout(0.3), # Protezione dai falsi positivi

        layers.Dense(32),
        layers.LeakyReLU(negative_slope=0.01),

        layers.Dense(32),
        layers.LeakyReLU(negative_slope=0.01),
        layers.BatchNormalization(),

        # Terzo blocco: Fine-tuning
        layers.Dense(16, activation='relu'),

        # Output: Risk Score
        layers.Dense(1, activation='sigmoid')
    ])

    # Optimizer con Learning Rate ridotto per maggiore stabilità
    opt = tf.keras.optimizers.Adam(learning_rate=0.0001)

    model.compile(
        optimizer=opt,
        loss='binary_crossentropy',
        metrics=[
            tf.keras.metrics.Precision(name='precision'),
            tf.keras.metrics.Recall(name='recall'),
            tf.keras.metrics.AUC(name='pr_auc', curve='PR') # Focus sulla curva Precision-Recall
        ]
    )
    return model

# Crea il modello
model_v3 = build_precision_model((X_train_scaled.shape[1],))
model_v3.summary()

import tensorflow as tf
from tensorflow.keras import layers, models

def build_precision_model(input_shape):
    model = models.Sequential([
        layers.Input(shape=input_shape),

        # Standard funnel - much cleaner for Backpropagation
        layers.Dense(512),
        layers.LeakyReLU(0.01),
        layers.BatchNormalization(),
        layers.Dropout(0.3),

        layers.Dense(256),
        layers.LeakyReLU(0.01),
        layers.BatchNormalization(),
        layers.Dropout(0.2),

        layers.Dense(128),
        layers.LeakyReLU(0.01),
        layers.BatchNormalization(),

        layers.Dense(64, activation='relu'),
        layers.Dense(16, activation='relu'),
        layers.Dense(1, activation='sigmoid')
    ])

    # Optimizer con Learning Rate ridotto per maggiore stabilità
    opt = tf.keras.optimizers.Adam(learning_rate=0.0001)

    model.compile(
        optimizer=opt,
        loss='binary_crossentropy',
        metrics=[
            tf.keras.metrics.Precision(name='precision'),
            tf.keras.metrics.Recall(name='recall'),
            tf.keras.metrics.AUC(name='pr_auc', curve='PR') # Focus sulla curva Precision-Recall
        ]
    )
    return model

# Crea il modello
model_v4 = build_precision_model((X_train_scaled.shape[1],))
model_v4.summary()

import tensorflow as tf
from tensorflow.keras import layers, models

def build_precision_model(input_shape):
    model = models.Sequential([
        layers.Input(shape=input_shape),

        # Standard funnel - much cleaner for Backpropagation
        layers.Dense(512),
        layers.LeakyReLU(0.01),
        layers.BatchNormalization(),
        layers.Dropout(0.3),

        layers.Dense(256),
        layers.LeakyReLU(0.01),
        layers.BatchNormalization(),
        layers.Dropout(0.2),

        layers.Dense(512),
        layers.LeakyReLU(0.01),
        layers.BatchNormalization(),
        layers.Dropout(0.3),

        layers.Dense(256),
        layers.LeakyReLU(0.01),
        layers.BatchNormalization(),
        layers.Dropout(0.2),

        layers.Dense(128),
        layers.LeakyReLU(0.01),
        layers.BatchNormalization(),

        layers.Dense(64, activation='relu'),
        layers.Dense(16, activation='relu'),
        layers.Dense(1, activation='sigmoid')
    ])

    # Optimizer con Learning Rate ridotto per maggiore stabilità
    opt = tf.keras.optimizers.Adam(learning_rate=0.001)

    model.compile(
        optimizer=opt,
        loss='binary_crossentropy',
        metrics=[
            tf.keras.metrics.Precision(name='precision'),
            tf.keras.metrics.Recall(name='recall'),
            tf.keras.metrics.AUC(name='pr_auc', curve='PR') # Focus sulla curva Precision-Recall
        ]
    )
    return model

# Crea il modello
model_v5 = build_precision_model((X_train_scaled.shape[1],))
model_v5.summary()

"""## Specify model"""

model = model_v5

import numpy as np

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()
total = neg + pos
weight_for_0 = (1 / neg) * (total / 2.0)
weight_for_1 = (1 / pos) * (total / 2.0)
class_weights = {0: weight_for_0, 1: weight_for_1}

early_stop = tf.keras.callbacks.EarlyStopping(
    monitor='val_pr_auc',
    patience=5,
    restore_best_weights=True,
    mode='max'
)

early_stop_prec = tf.keras.callbacks.EarlyStopping(
    monitor='val_pr_auc',
    patience=10,
    restore_best_weights=True,
    mode='max'
)

print("Starting training...")

history = model.fit(
    X_train_scaled,
    y_train,
    validation_data=(X_val_scaled, y_val),
    epochs=1000,
    batch_size=8192,
    class_weight=class_weights,
    #callbacks=[early_stop_prec],
    verbose=1
)

results = model.evaluate(X_test_scaled, y_test, verbose=1)
print(f"AUC test: {results[2]:.4f}")

y_pred_prob = model.predict(X_test_scaled)

# treshold to determine fire/nofire
y_pred = (y_pred_prob > 0.95).astype(int)

from sklearn.metrics import classification_report, confusion_matrix
print("\nConfusion Matrix:")
print(classification_report(y_test, y_pred))

import joblib

# Save the scaler
joblib.dump(scaler, '/content/drive/MyDrive/Models/WEDS - RiskScore/data_scaler_v5_1000.pkl')

# Save the model
model_v5.save('/content/drive/MyDrive/Models/WEDS - RiskScore/fire_risk_model_v5_1000.keras')

print("<SUCCESS> Model saved as fire_risk_model_v4.keras")

"""## Statistics"""

import matplotlib.pyplot as plt

def plot_learning_curves(history):
    # Verifichiamo i nomi delle chiavi (cambiano se hai usato 'auc' o 'pr_auc')
    keys = history.history.keys()

    # Cerchiamo la metrica AUC (che sia pr_auc o auc standard)
    auc_key = 'pr_auc' if 'pr_auc' in keys else 'auc'
    val_auc_key = 'val_pr_auc' if 'val_pr_auc' in keys else 'val_auc'

    acc = history.history[auc_key]
    val_acc = history.history[val_auc_key]
    loss = history.history['loss']
    val_loss = history.history['val_loss']
    epochs = range(1, len(acc) + 1)

    plt.figure(figsize=(15, 5))

    # Grafico AUC
    plt.subplot(1, 2, 1)
    plt.plot(epochs, acc, 'bo-', label=f'Training {auc_key}')
    plt.plot(epochs, val_acc, 'ro-', label=f'Validation {auc_key}')
    plt.title(f'Training and Validation {auc_key.upper()}')
    plt.xlabel('Epochs')
    plt.ylabel('Score')
    plt.legend()

    # Grafico Loss
    plt.subplot(1, 2, 2)
    plt.plot(epochs, loss, 'bo-', label='Training Loss')
    plt.plot(epochs, val_loss, 'ro-', label='Validation Loss')
    plt.title('Training and Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()

    plt.show()

plot_learning_curves(history)

from sklearn.metrics import precision_recall_curve

precision, recall, thresholds = precision_recall_curve(y_test, y_pred_prob)

plt.figure(figsize=(8, 6))
plt.plot(recall, precision, color='darkorange', lw=2)
plt.xlabel('Recall (Capacità di beccare gli incendi)')
plt.ylabel('Precision (Attendibilità dell\'allarme)')
plt.title('Curva Precision-Recall')
plt.grid(True)
plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
plt.xlabel('Predicted')
plt.ylabel('Real')
plt.title('Confusion Matrix')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

def plot_probability_distribution(model, X_test_scaled):
    """
    Plots the recurrence (frequency) of each risk score probability.
    """
    # 1. Get raw Sigmoid outputs (values between 0 and 1)
    print("Generating predictions...")
    y_probs = model.predict(X_test_scaled, batch_size=8192).flatten()

    # 2. Create the plot
    plt.figure(figsize=(10, 6))

    # We use 50 bins to see the distribution in 2% increments
    counts, bins, patches = plt.hist(y_probs, bins=50, color='skyblue', edgecolor='black', alpha=0.7)

    # 3. Customizing the labels
    plt.title('Risk Score Distribution (Number of Recurrences vs. Probability)', fontsize=14)
    plt.xlabel('Probability (Risk Score 0.0 to 1.0)', fontsize=12)
    plt.ylabel('Number of Occurrences (Frequency)', fontsize=12)

    # Optional: Log scale if the 0.0 class (no fire) is so large it hides the others
    # plt.yscale('log')

    plt.grid(axis='y', linestyle='--', alpha=0.7)

    # 4. Adding a vertical line for the standard 0.5 threshold
    plt.axvline(x=0.5, color='red', linestyle='--', label='Default Threshold (0.5)')
    plt.legend()

    plt.show()

    # Summary Statistics
    print(f"Mean Risk Score: {np.mean(y_probs):.4f}")
    print(f"Max Risk Score: {np.max(y_probs):.4f}")
    print(f"Min Risk Score: {np.min(y_probs):.4f}")

# Execute the function
plot_probability_distribution(model, X_test_scaled)

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

def plot_risk_separation(model, X_test_scaled, y_test):
    """
    Plots the distribution of Risk Scores separated by actual Fire / No Fire labels.
    """
    print("Calculating predictions...")
    y_probs = model.predict(X_test_scaled, batch_size=8192).flatten()

    plt.figure(figsize=(12, 7))

    # Create masks for the two classes
    fire_mask = (y_test == 1)
    no_fire_mask = (y_test == 0)

    # Plot Distribution for No Fire
    sns.kdeplot(y_probs[no_fire_mask],
                fill=True, color="blue", label="Actual: No Fire",
                bw_adjust=0.5, common_norm=False)

    # Plot Distribution for Fire
    sns.kdeplot(y_probs[fire_mask],
                fill=True, color="red", label="Actual: Fire",
                bw_adjust=0.5, common_norm=False)

    # Formatting
    plt.title('Risk Score Discrimination: Fire vs No Fire', fontsize=15)
    plt.xlabel('Model Risk Score (Probability)', fontsize=12)
    plt.ylabel('Density (Normalized)', fontsize=12)
    plt.xlim(0, 1) # Probability is always 0 to 1
    plt.grid(axis='y', linestyle='--', alpha=0.3)
    plt.legend()

    # Add descriptive text
    plt.annotate('Overlap Area = Uncertainty', xy=(0.5, 0.1), xytext=(0.4, 0.5),
                 arrowprops=dict(facecolor='black', shrink=0.05),
                 fontsize=12, color='black')

    plt.show()

# Run the plot
plot_risk_separation(model, X_test_scaled, y_test)

"""# TinyML

Then it is time to transform from a model to a tinyML model.

"""

to_tiny_path = '/content/drive/MyDrive/Models/WEDS - RiskScore/tiny/'
version_number = 5_500

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

open(f"{to_tiny_path}fire_risk_tmodel_v{version_number}.tflite", "wb").write(tflite_model)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT] # This enables quantization

tflite_quant_model = converter.convert()

# Save for Deployment
with open(f"{to_tiny_path}fire_risk_tmodel_quant_v{version_number}.tflite", "wb") as f:
    f.write(tflite_quant_model)

